# This file is covered by the LICENSE file in the root of this project.
name: "kitti"
labels:
# 1.车 2.人 3.非机动车 4.可通行区域
  0: "unlabeled" # 未标注
  1: "outlier" # 离群点
  10: "car" # 汽车
  11: "bicycle" # 自行车
  13: "bus" # 公交车
  15: "motorcycle" # 摩托车
  16: "on-rails" # 轨道车
  18: "truck" # 卡车
  20: "other-vehicle" # 其他车辆
  30: "person" # 行人
  31: "bicyclist" # 骑自行车的人
  32: "motorcyclist" # 骑摩托车的人
  40: "road" # 道路
  44: "parking" # 停车场
  48: "sidewalk" # 人行道
  49: "other-ground" # 其他地面
  50: "building" # 建筑物
  51: "fence" # 围栏
  52: "other-structure" # 其他结构物
  60: "lane-marking" # 车道标线
  70: "vegetation" # 植被
  71: "trunk" # 树干
  72: "terrain" # 地形
  80: "pole" # 杆子
  81: "traffic-sign" # 交通标志
  99: "other-object" # 其他物体
  252: "moving-car" # 移动的汽车
  253: "moving-bicyclist" # 移动的骑自行车的人
  254: "moving-person" # 移动的行人
  255: "moving-motorcyclist" # 移动的骑摩托车的人
  256: "moving-on-rails" # 移动的轨道车
  257: "moving-bus" # 移动的公交车
  258: "moving-truck" # 移动的卡车
  259: "moving-other-vehicle" # 移动的其他车辆
color_map: # bgr
  0: [20, 20, 20]
  1: [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 0, 0]
#  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0: 0     # "unlabeled"
  1: 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 1     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 2     # "motorcycle"
  16: 1     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 1     # "truck"
  20: 1     # "other-vehicle"
  30: 3     # "person"
  31: 2     # "bicyclist"
  32: 2     # "motorcyclist"
  40: 4     # "road"
  44: 4    # "parking"
  48: 4    # "sidewalk"
  49: 4    # "other-ground"
  50: 5    # "building"
  51: 5    # "fence"
  52: 5     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 4     # "lane-marking" to "road" ---------------------------------mapped
  70: 5    # "vegetation"
  71: 5    # "trunk"
  72: 5    # "terrain"
  80: 5    # "pole"
  81: 5    # "traffic-sign"
  99: 5     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 2    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 3    # "moving-person" to "person" ------------------------------mapped
  255: 2    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 1    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 1    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 1    # "moving-truck" to "truck" --------------------------------mapped
  259: 1    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 30     # "person"
  4: 40     # "road"
  5: 50     # "background"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  6: False     # "person"
  7: False     # "bicyclist"
  8: False     # "motorcyclist"
  9: False     # "road"
  10: False    # "parking"
  11: False    # "sidewalk"
  12: False    # "other-ground"
  13: False    # "building"
  14: False    # "fence"
  15: False    # "vegetation"
  16: False    # "trunk"
  17: False    # "terrain"
  18: False    # "pole"
  19: False    # "traffic-sign"
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  valid:
    - 0
  test:
    - 4

